name: Sync to Hugging Face
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          rm -rf images/ data/raw/ *.ipynb
          git add .
          git commit -m "Strip binaries for Hugging Face deployment" || echo "No changes to commit"
          git push --force https://yosakornn:$HF_TOKEN@huggingface.co/spaces/yosakornn/stock-sentiment-analysis main
